public interface Engine {
    
    //1)'Interface' icindeki MEthodlar Otomatik olarak
    //Public tir. Bu yuzden Interfacelerde Method olustururken
    //Access Modifier yazmayiz.
    //
    //2)Interface icindeki methodlar otomatik olarak
    //ABSTRACT dir.Bu yuzden Interfacelerde Method olustururken
    //'Abstract' keyword unu ve 'MEthod Body' sini yazmayiz.
    
    void eco();
    
    void turbo();
    
    void gas();
}