public class Mo1 {
    
    Public Integer MethodMo1(Integer a, Integer b){
        return(a+b);
    }
    Public Integer MethodMo1(Integer a, Integer b, Integer c){
        return(a+b+c);
    }
    Public Decimal MethodMo1(Decimal a, Integer b){
        return(a+b);
    }
    Public Decimal MethodMo1(Integer a, Decimal b){
        return(a+b);
    }
    Public Decimal MethodMo1(Decimal a, Decimal b){
        return(a*b);
    }
}